name: Generate Docs
on: 
  workflow_dispatch:
    inputs:
      latestVersion:
        description: 'Whats the latest version of the SDK?'
        required: true

permissions:
  contents: write
  pull-requests: write # create new PR

jobs:

  Generate:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744  # 3.6.0
      with:
        fetch-depth: 0
    - uses: n1hility/cancel-previous-runs@e709d8e41b16d5d0b8d529d293c5e126c57dc022 #v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd #v1.6.0
      with:
        xcode-version: 16.4

    - name: Generate Docs
      run: |
        .github/scripts/generate-docs.sh
      env:
        VERSION: ${{ github.event.inputs.latestVersion }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e #v7.0.8
      with:
        delete-branch: true
        branch: update-docs-github-action
        commit-message: "chore: updated documentation"
        title: update documentation
        body: Regenerate documentation.
        token: ${{ secrets.GITHUB_TOKEN }}